version: "3.6"
services:
  service:
    build:
      dockerfile: docker/service/Dockerfile.service
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - ./service:/app
    environment:
      - DISPLAY=:10
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - data_store:/var/lib/mysql
volumes:
  data_store:
